### ISSUE TITLE
undefined: zk.WithLogger

### ISSUE THREAD

**Issue by Minger** [DecipherNow/gm-fabric-go#149]
on `go  build` in another project with gm as a dependency:

v0.1.3

```
# github.com/deciphernow/pushdown-automaton-service/vendor/github.com/deciphernow/gm-fabric-go/gk
../../vendor/github.com/deciphernow/gm-fabric-go/gk/pkg.go:195:56: 
```

**Comment by joshua-rutherford** [comment]
Did this build before? If so, I'd recommend pinning your dependency to v0.1.2 or a previous release that worked.  @dougfort, do you recall the release prior to when that went in?

I really think we need to be expressly pinning all dependencies in our services and applications.  For libraries be permissive with dependencies makes more sense.  Granted, I recognize that we have not been semantically versioning this so it is on us as well.

**Comment by dougfort** [comment]
We were getting that same error in CircleCI. It's some outdated library. What does 'pin' mean?

**Comment by joshua-rutherford** [comment]
I don't see any failures in CircleCI?

I simply mean that he could use `=0.1.2` for his constraint in his `Gopgk.toml`.

**Comment by Minger** [comment]
I'm moving the pda project to `dep` from `govendor` just so I can pin the version--to `v0.1.0` just to be safe.

zk got `WithLogger` in this commit https://github.com/samuel/go-zookeeper/commit/fb0920525b424dc4761729bcc7ade50d7988fa5a#diff-5f455e42d3680fdc56c7076dc0c182f3

However, doing a search on this repo, I don't see `samuel` outside the two package declarations in `/zk`, `/gk`, ie they are not listed in `Gopkg.toml` or `Gopkg.lock`

**Comment by dougfort** [comment]
https://circleci.com/gh/DecipherNow/gm-fabric-go/163

CircleCI doesn't fail any more because it somehow got the right versions

**Comment by dougfort** [comment]
gm-fabric-go doesn't vendor anything: it is a library.

**Comment by joshua-rutherford** [comment]
@dougfort, realizing that it is a library and shouldn't have a `Gopkg.lock`, a `Gopkg.toml` with optimistic dependency locking is probably in order.  For example, we know if someone brings in certain versions of the aws-go-sdk it breaks us builds on some machines.

**Comment by joshua-rutherford** [comment]
@Minger, I don't have an issue with bringing in `Gopkg.toml` but there have to be some logical assumptions to do that without being overly restrictive on users of the library.  Specifically, we should specify constraints in the `Gopkg.toml` in a manor that allows the maximum amount of flexibility in downstream projects.  Note that your example uses a very loose restriction on it's only constrained dependency:

```
[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = ">=1.0.0, <=3.0.0-g6d21280"
```

That is what we should be doing in all libraries, only constraining ourselves from break points.  It is possible for dependent projects to `[[override]]` our `[[constraints]]` but then it's on them to handle the breakages.  

I've done a simple program with the above library and this code:

```
package main

import (
    "fmt"
    "github.com/stretchr/testify/assert" 
    "`"
)

func main() {
    info := assert.CallerInfo()
    matcher := difflib.NewMatcher(info, info)
    for index, element := range assert.CallerInfo() {
        fmt.Printf(fmt.Sprintf("%d : %s\n", index, element))
    }
    fmt.Printf(fmt.Sprintf("percent match: %f\n", matcher.Ratio()))
}
```

When I add a `[[constraint]]` on `github.com/pmezard/go-difflib/difflib`, a library that is not in the upstream `Gopkg.toml` but is in the `Gopkg.lock`, I am fine running `dep ensure` with any version of `github.com/pmezard/go-difflib/difflib`.  Granted, the code may not compile or run.

However, if I add a `[[constraint]]` on `github.com/davecgh/go-spew`, a library that is in both the upstream `Gopkg.toml` and the `Gopkg.lock`, `dep` is unable to find a solution to the dependency graph if my `[[constraint]]` is not within the constraints in the upstream `Gopkg.toml` (`>=1.0.0, <=3.0.0-g6d21280`).  Note that if I add an `[[override]]` instead of a `[[constraint]]`, `dep` will just assume I know what I'm doing and force that version rather than finding a solution that includes it.  And as a result, my code won't compile if the version is before `1.0.0`.

This is all a long winded way of saying I'm okay with adding `Gopkg.toml` to restrict users from using versions of dependencies we know don't work.  Does that make sense.

**Comment by joshua-rutherford** [comment]
@dougfort, see above.  I think I empirically proved that `dep` does not even pay attention to `Gopkg.lock` in dependencies.  Therefore, there is no benefit to end users of the SDK as it will be ignored in their builds (and I assume the vendor directory too).  Therefore it is only of benefit when building the library alone as in the case of tests.  

That said, I'm niether for or against adding `Gopkg.lock` or `vendor` to the repository.  I think a properly constrained `Gopkg.toml` is probably more appropriate though as our builds will then reflect what someone consuming the library is likely to get for dependencies out of `dep`.

@cstrahan, @alecholmez, thoughts?

**Comment by joshua-rutherford** [comment]
@Minger for now I'd recommend adding the following lines to your `Gopkg.toml`:

```
[[override]]
  name = "github.com/samuel/go-zookeeper"
  revision = "c4fab1ac1bec58281ad0667dc3f0907a9476ac47"
```

@dougfort, @cstrahan and @dougfort, since this dependency has no tags and `dep` doesn't have any mechanism to say `revision = ">= c4fab1ac1bec58281ad0667dc3f0907a9476ac47"` we should think about this a bit as in this case we can either very much constrain our users with the exact commit (i.e.,`revision = "c4fab1ac1bec58281ad0667dc3f0907a9476ac47") or accept some volatility with `branch = "master"`.

**Comment by alecholmez** [comment]
Closing this. Community frowns upon checking in `Gopkg.*` files in libraries and you should never check in `vendor` folders

**Comment by joshua-rutherford** [comment]
@alecholmez, can you site where your "Community" reference comes from?  I find it hard to believe that, since optimistic locking is available, people wouldn't want to establish the parameters under which their code is known to work.
