### ISSUE TITLE
Create Template Cache

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-go#153]
This is a step towards #146 and #147 

We have several templates embedded in the fabric source code in ```genproto```. The main one is the gateway proxy template which is quite large. 

These templates aren't in ```gm-templates-go``` because they aren't used until the ```--generate``` stage. 

I would like to establish a template cache for templates that aren't immediately used in ```--init```. This could be useful in many ways as we make the generator more flexible.

**Comment by joshua-rutherford** [comment]
Where is the cache going to reside.  I assume it's in the template online and brought down when fetched and used to build on generate.

**Comment by dougfort** [comment]
We're going to need some kind of local storage. We might need it for #146 too. Perhaps ```.fabric/template-cache``` right under the top level service directory.

**Comment by dougfort** [comment]
So we just copy ```default/template-cache``` into ```<local>/template-cache``` and fabric needs to know enough to look in the cache for templates during ```--generate```

**Comment by joshua-rutherford** [comment]
I'm good with this but

**Comment by dougfort** [comment]
OK, that looks good to me

**Comment by joshua-rutherford** [comment]
Yes, but they can get rendered by it but not as templates themselves into the `.fabric/templates` directory of the project.  I think the only issue is that we will be nesting templates within templates so we need to confirm that there is a why to mark something as raw so that go templates doesn't attempt to inject variables at `init` that we expect to be injected at `generate`.

**Comment by dougfort** [comment]
We inject a stub gateway proxy handler at ```--init```, so  the program will compile. Then we write over it in ```--generate``` when we have the generated gateway proxy code. 

We have generic method templates that get used in ```--generate``` when the user defines specific RPC calls in the .proto file.

**Comment by joshua-rutherford** [comment]
Yes, I thought the goal here was to move the generic method templates into the template repo too, right?

**Comment by dougfort** [comment]
um, no. To store them in the template cache for later use.

**Comment by joshua-rutherford** [comment]
Where will you move them from to put them in the template cache?

**Comment by dougfort** [comment]
I will keep the templates in the cache and render the code into the appropriate source file.

**Comment by joshua-rutherford** [comment]
I don't think you need to handle it ass a special case at all.  I totally forsee a case where those templates used in generate could be populated with some variables in init.  The issue is that those files would be rendered by the template engine twice.  Once on `init` and then again on `generate` so they would have to be prepared accordingly. 

If I wanted my template in the project to be:
```
blah
blah
blah
{{.Value "variable"}}
```
I would have to do it like so in the template repo:
```
blah
blah
blah
{{"{{.Value \"variable\"}}"}}
```
I know this makes the template more difficult to write but I hate having special cases in code as they make assumptions that invariably turn out false (like we'll never want anything in that fabric directory to be rendered as a template and I will actually probably want to capture the variables provided at `init` in there so I can use them later in other scripts).

**Comment by joshua-rutherford** [comment]
Also, most templating engines have the ability to turn of rendering in portions of the file entirely but I don't see that with go templates.  If that is available that is the obvious choice.

**Comment by dougfort** [comment]
OK

**Comment by joshua-rutherford** [comment]
That sounds like I wore you down, not like you actually agree.

**Comment by dougfort** [comment]
I still hate the callback. I don't like this either. I'm a professional. I'll give it my best shot.
