### ISSUE TITLE
Break out errors by status code using Finagle structure

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-go#172]
## Status Quo

`gm-fabric-go` microservices generate a count of all errors called `errors.count`

An example of this is at https://edge.deciphernow.com/fabric/#/up2-service-v1-0/076d25244c874dffbebe56130f1edf38/explorer?filterString=errors.count

In contrast to this, `gm-fabric-jvm` generates separate counts for the different status codes and 2XX, 4XX, 5XX rollups. These exist for routes and across all routes.

An example of this is at https://edge.deciphernow.com/fabric/#/discovery-service-v1-0/cfa674db67444d87c8465e23f14995a3/explorer?filterString=status%2F

The Finagle docs discuss these metrics at https://twitter.github.io/finagle/guide/Metrics.html#http

## Proposed Enhancement:

I propose that we enhance `gm-fabric-go` to mirror the Finagle api to allow UI work (https://github.com/DecipherNow/gm-fabric-dashboard/issues/1526) to visually differentiate between client side and server site errors.

**Comment by dougfort** [comment]
I think this is related to #169

**Comment by rfielding** [comment]
Note that there is a gray area in these codes, and this is how we handled it in odrive:

```
[400,499] -- bad input from client -- "blame the user"
[500,599] -- internal server error of some kind -- "blame the server"
```
When we use micro services that recursively call back into each other, it becomes harder to assign blame.  If a client gives us a perfectly well-formed request, and the server code is actually perfect, but the backend service that we call (an authentication service for instance) is down.... It isn't the caller's fault, so it's not 4xx.  The server isn't really at fault either, so it's not really 5xx.  

I think in object-drive, we have a few places where we just add 1000 to the status code, so that it's possible to get something like: 1404.  Which means that the server experienced a fault, that was caused by an external dependency; and it's not the client's fault.  In this case, something wasn't found in the backend.  In any case, it's above 499, so there is nothing that the client can do.  If we transform this to anything, we might have to transform this into an http code asking to try later (which kind of needs an indication of _when_ to try again ... ie: wait 30s).

Remember that the API needs to be following a well-defined state machine.  ie: You can't download a file that has never been uploaded.  If something is not yet available, maybe tell you to wait a little longer and expect a 200 later.

At Google, 5xx rate counting is used to stop disasters from spreading when code is deployed.

I can't stress enough.... there are parts where we can make up whatever wacky thing we want (mostly the grpc parts).  But parts that are called by existing browser components, will not work correctly if we don't obey the behavior expected by existing browser implementations.

**Comment by rfielding** [comment]
This gets discussed a lot.  It's not always obvious what the solution is:

https://stackoverflow.com/questions/9794696/how-do-i-choose-a-http-status-code-in-rest-api-for-not-ready-yet-try-again-lat

**Comment by rfielding** [comment]
Note about the 202 suggestions:  If 202 had a mandatory time-to-try-again, then the semantics would be simple:  while you get a 202, look in the header to figure out how long to wait.  Eventually you will get a 200, or some kind of actual error.

**Comment by rfielding** [comment]
note also: httpmetrics is not the same handler as grpcmetrics.  i don't know how you guys would plan to mark grpcmetrics return codes to correctly distinguish between bad-user-input versus server-bug versus backend-fault.
