### ISSUE TITLE
HTTP OPTIONS error from gateway proxy

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-go#202]
Fabric framework... I am getting a 401 in response to an OPTIONS request.  The only possible way that my code returns an error is to return a 400 if no Origin set, which it is.  With layers of handlers, perhaps OPTIONS is handled earlier and causing my problem:
```OPTIONS 401 Unauthorized: failed to load [url].  response for preflight has invalid status code 401.```
something like that.  is OPTIONS handled earlier or something?

**Comment by rfielding** [comment]
I was doing a lot of research on this last night.  There is definitely an issue once OPTIONS reach our services.  But the problem is actually even deeper than this as well.

It is considered to be a bug that in Chrome, OPTION even gets a client certificate.  The spec says that when using client certs, to NOT send the client cert during an OPTION.  I can't even imagine a situation in which that is practical.  It's saying that our microservices should be getting possibly unauthenticated client connections, and we need to look at the request and deny it for lacking a client certificate.

https://stackoverflow.com/questions/40663641/cors-with-client-https-certificates

That's ridiculous though, because we need to audit everything.  If a client comes in without a client cert, then it should not be given a connection.  Which leads to this thread:

https://bugzilla.mozilla.org/show_bug.cgi?id=1019603#c9

I did manage to write a POC that I had CORS working in odrive some time last year.  I manually set on the XMLHttpObject the sendCredentials and crossDomain flags as required.  That made it work in Chrome, which apparently is a bug(!!) according to the spec.  So that means that this would only work in Chrome, and still be broken everywhere else.

So, following this around, I now conclude that the only way to make CORS work correctly and _portably_ across browsers is to make NGINX respond to OPTIONS itself with a 200, to keep this from reaching our microservices at all.  Nginx would get the connection over TLS that has no client cert for OPTIONS, and just return a 200 for us; because our microservices cannot be sent such requests.  They would end up getting to our ServeHTTP interceptor and we have code to reject non-OPTIONS requests.

https://gist.github.com/icepol/55f4d0dd8235f47aa4ec

**Comment by rfielding** [comment]
@7ruth

**Comment by rfielding** [comment]
Though note a subtlety created by nginx as proxy.  The nginx server would get a connection over TLS where the client has no certificate.  Then nginx would connect to the upstream with the nginx identity cert, which our service trusts.  So then our ServeHTTP handlers would be getting something that has a client cert and happens to have an OPTION verb.  A browser can't do this according to spec, but this happens because of the proxy in the middle.

So, if we were to pass on the OPTION, then the nginx config needs to do something so that it's ok to the backend.  It would be like an impersonation as "nobody".

**Comment by rfielding** [comment]
And for background, this is where I was when I was wrestling with this when I added CORS into odrive:

https://stackoverflow.com/questions/40663641/cors-with-client-https-certificates

Basically, the entire DoD (who else uses PKI?) has this issue.
