### ISSUE TITLE
API backwards compatibility with non-Fabric service versions

### ISSUE THREAD

**Issue by Minger** [DecipherNow/gm-fabric-go#215]
1) the HTTP REST endpoints of legacy services being converted using this SDK to an equivalent protobuf service backing HTTP requests via gRPC gateway reverse proxy must experience *some* change in the contract

2) the least change in the HTTP api contract in some instances requires the most service legacy code modification while the least service modification may require the biggest contract changes.

The challenge of this SDK for supporting the conversion of legacy HTTP services is minimizing both the API contract and internal service code at the same time.  (Some API contract modification seems unavoidable due to the constraints of the protobuf specification: one root key must exist and it is the parent protobuf message name. The legacy endpoint request body has four peer keys.) 

I'll illustrate with a simple example: I have a legacy service with an endpoint that takes a post request with a json body; the json is deeply nested with specific keys and values expected by the service.  The service request handling takes the json as a string, validates specifics of the json, and then converts it to a struct that has a lot of code depending on it to be a struct.

(The legacy service has a dozen or so endpoints.  I discuss here only the one I worked on.)

The least change to the contract, adding a root key to the json, required massive code changes to use the protobuf messages.  Defining equivalent nested protobuf messages for the request deeply nested json and getting the service to use them was part of the challenge.  (Nested jsons are no challenge for the legacy service because it leverages libraries that easily manipulate json as json without the need for structs as an intermediary.)

The easiest conversion path was to simply preserve as much existing logic starting at the original http request boundary, which takes the request body json as a string, and to make all the necessary modifications to the incoming Fabric code to preserve the functionality of the service.  This least painful development path caused the biggest change to the API: the request body changed from a specific json to a body with that json serialized as a string value two keys deep.

There's no magic solution that can preserve the legacy API contracts.  The trade-offs are between doing a lot of work to existing legacy code for the least change api or making the least changes to legacy code at the cost of drastic contract changes--also to be borne by service users.  (Even if the SDK could hack the requirement presence for a message root key, thus preserving the contract for that one endpoint 100%, the substantial service work to replace structs with protobuf messages cannot be reduced or eliminated.)

**Comment by AsataPDN** [comment]
@danielpcox and @joshua-rutherford  Would you prefer we pile our issues into this or create an epic and link individual issues to it?

**Comment by rfielding** [comment]
@Minger I had a similar issue with gm-data.  The two most important endpoints in gm-data don't have a reasonable grpc representation.  And there is little point in having an incomplete (unusable on its own) part of the API be in grpc; so the whole thing is straightforward go standard-library REST with json.

You can use an existing ServerHTTP function with gm-fabric-go.  You just need to intercept the handler in gateway_proxy.go:

```
	var hdlr http.Handler = &fileHandler{
		Ctx:         ctx,
		Mux:         mux,
		HandlerFunc: hFunc,
	}

	if viper.GetBool("verbose_logging") {
		stack := middleware.Chain(
			middleware.MiddlewareFunc(hlog.NewHandler(logger)),
			middleware.MiddlewareFunc(hlog.AccessHandler(func(r *http.Request, status int, size int, duration time.Duration) {
				hlog.FromRequest(r).Info().
					Str("method", r.Method).
					Str("path", r.URL.String()).
					Int("status", status).
					Int("size", size).
					Dur("duration", duration).
					Msg("Access")
			})),
			middleware.MiddlewareFunc(hlog.UserAgentHandler("user_agent")),
		)
		hdlr = stack.Wrap(hdlr)
	}
```

Due to this, I actually can produce two binaries (cmd/server vs cmd/gmdatad).  One binary in cmd/server starts up using gm-fabric-go, and is meant to be hosted in the fabric runtime as a container.  The other binary in cmd/gmdatad uses some of the gm-fabric-go library (viper to read in env vars, zero log logging, etc), but that binary is meant to run on end-to-end clients (ie: Windows, Linux, or OSX desktop systems) - and is therefore outside the scope of fabric.

**Comment by alecholmez** [comment]
This is less an issue of the SDK and more of an issue with gRPC itself. When using the SDK you are buying into Google's HTTP/2 and GRPC/Protobuf paradigms which are inherently a major shift from HTTP/1.1 and REST/JSON. We only provide the gateway because so much legacy architecture and applications are dependent upon such an interface. In a perfect scenario, everyone would be speaking HTTP/2 and GRPC with streams. Obviously, this isn't achievable at this moment so preserving the legacy contract between App and Service will take work. I had to refactor services with major updates but it's one of the reasons why we cut a 2.0 release. When massive API changes are required then it's safe to call that a breaking release.

I'm not sure this is a good place for this issue. The complaints filed are towards GRPC and Protobuf and I'm very against writing a hack for a specific use case in a public facing product
